// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96M9dc1gjlq45KJJI6p6V0OQMYIB4pNM',
    appId: '1:111776219660:web:e82cef618ad6d24dd8a429',
    messagingSenderId: '111776219660',
    projectId: 'hackthonproject-70499',
    authDomain: 'hackthonproject-70499.firebaseapp.com',
    storageBucket: 'hackthonproject-70499.appspot.com',
    measurementId: 'G-RRLYV3F2DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcfDAb8lsonI12EXhYVaV2mtj06cyPcU',
    appId: '1:111776219660:android:7ec45121d7a23f52d8a429',
    messagingSenderId: '111776219660',
    projectId: 'hackthonproject-70499',
    storageBucket: 'hackthonproject-70499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32ouMTso8hNMGJXWMvERzg8ljwqu9GCw',
    appId: '1:111776219660:ios:e628e6a10e253606d8a429',
    messagingSenderId: '111776219660',
    projectId: 'hackthonproject-70499',
    storageBucket: 'hackthonproject-70499.appspot.com',
    iosClientId: '111776219660-ji2sru7ppqqmhmvdvmbggci9a2t6u763.apps.googleusercontent.com',
    iosBundleId: 'com.example.hacktonflutter',
  );
}
